<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: package/v1/package_api.proto

namespace Package\V1\Package;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>package.v1.Package.Links</code>
 */
class Links extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string package = 1;</code>
     */
    private $package = '';
    /**
     * Generated from protobuf field <code>string homepage = 2;</code>
     */
    private $homepage = '';
    /**
     * Generated from protobuf field <code>string repository = 3;</code>
     */
    private $repository = '';
    /**
     * Generated from protobuf field <code>string bugs = 4;</code>
     */
    private $bugs = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $package
     *     @type string $homepage
     *     @type string $repository
     *     @type string $bugs
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Package\V1\PackageApi::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string package = 1;</code>
     * @return string
     */
    public function getPackage()
    {
        return $this->package;
    }

    /**
     * Generated from protobuf field <code>string package = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPackage($var)
    {
        GPBUtil::checkString($var, True);
        $this->package = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string homepage = 2;</code>
     * @return string
     */
    public function getHomepage()
    {
        return $this->homepage;
    }

    /**
     * Generated from protobuf field <code>string homepage = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setHomepage($var)
    {
        GPBUtil::checkString($var, True);
        $this->homepage = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string repository = 3;</code>
     * @return string
     */
    public function getRepository()
    {
        return $this->repository;
    }

    /**
     * Generated from protobuf field <code>string repository = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setRepository($var)
    {
        GPBUtil::checkString($var, True);
        $this->repository = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string bugs = 4;</code>
     * @return string
     */
    public function getBugs()
    {
        return $this->bugs;
    }

    /**
     * Generated from protobuf field <code>string bugs = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setBugs($var)
    {
        GPBUtil::checkString($var, True);
        $this->bugs = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Links::class, \Package\V1\Package_Links::class);

