<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: package/v1/package_api.proto

namespace Package\V1;

if (false) {
    /**
     * This class is deprecated. Use Package\V1\Package\Links instead.
     * @deprecated
     */
    class Package_Links {}
}
class_exists(Package\Links::class);
@trigger_error('Package\V1\Package_Links is deprecated and will be removed in the next major release. Use Package\V1\Package\Links instead', E_USER_DEPRECATED);

